---
  timezone: Asia/Shanghai

  # Docker
  docker_install_compose_plugin: true
  docker_users:
    - "{{ current_username.stdout }}"

  # Samba
  samba_users:
    - name: "{{ current_username.stdout }}"
      password: vagrant

  samba_shares:
    - name: dev
      comment: 'Main dev folder'
      group: "{{ current_username.stdout }}"
      write_list: +{{ current_username.stdout }}
      guest_ok: 'no'
      path: /home/{{ current_username.stdout }}/dev