---
  timezone: Asia/Shanghai

  # Docker
  docker_install_compose_plugin: true
  docker_users:
    - "{{ current_username.stdout }}"

  # NFS
  nfs_exports:
    - /home/{{ current_username.stdout }}/dev *(rw,sync,no_root_squash,no_subtree_check)
