---
- name: Configure host.
  hosts: all
  become: true

  vars_files:
    - default.config.yml

  roles:
    - geerlingguy.docker
    - rolehippie.starship

  pre_tasks:
    - name: Ensure a locale exists
      community.general.locale_gen:
        state: present
        name: C.UTF-8

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

    # https://askubuntu.com/a/1479526/7641
    - name: Enable snapd installation.
      command: mv /etc/apt/preferences.d/nosnap.pref /etc/apt/preferences.d/nosnap.pref.disabled
      args:
        removes: /etc/apt/preferences.d/nosnap.pref
        creates: /etc/apt/preferences.d/nosnap.pref.disabled

    # https://stackoverflow.com/a/26399105/157811
    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: current_username

    - name: Ensure dotconfig directory exists.
      become: false
      file:
        path: /home/{{ current_username.stdout }}/.config
        state: directory

    - name: Dot config git directory.
      stat:
        path: /home/{{ current_username.stdout }}/.config/.git
      register: dotconfig_git

    - name: Add fish shell PPA
      apt_repository:
        repo: ppa:fish-shell/release-3
        state: present

    - name: Apt Install required softwares
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg: ['git', 'vim', 'fish', 'tmux', 'zip', 'unzip', 'build-essential', 'cmake',
              'curl', 'snapd', 'net-tools', 'apt-transport-https', 'ca-certificates']
        state: present

    - name: Install snap packages with option --classic
      community.general.snap:
        name:
          - nvim
        classic: true

  tasks:
    - name: Create main directory for development workspace.
      become: false
      file:
        path: /home/{{ current_username.stdout }}/dev
        state: directory

    - name: Include Samba Server role
      ansible.builtin.include_role:
        name: vladgh.samba.server

    - name: Setup dotconfig
      become: false
      command: "{{ item }}"
      args:
        chdir: /home/{{ current_username.stdout }}/.config
      with_items:
        - "git init"
        - "git remote add origin https://github.com/harryxu/dotconfig.git"
        - "git fetch"
        - "git checkout origin/main -ft"
        - "git submodule init"
        - "git submodule update"
      when: not dotconfig_git.stat.exists

    - name: Change user shell to fish
      user:
        name: "{{ current_username.stdout }}"
        shell: /usr/bin/fish
