---
- name: Configure host.
  hosts: all
  become: true
  vars_files:
    - default.config.yml

  roles:
    - geerlingguy.docker

  pre_tasks:
    - name: Install required softwares
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg:
          - git
          - vim
          - zsh
          - tmux 
          - apt-transport-https
          - ca-certificates
          - curl
          - zip
          - unzip
        state: present
