---
- name: Configure host.
  hosts: all
  become: true
  vars_files:
    - default.config.yml

  roles:
    - geerlingguy.docker

  pre_tasks:

    # https://stackoverflow.com/a/26399105/157811
    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: current_username

    - name: Install required softwares
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg:
          - git
          - vim
          - zsh
          - tmux 
          - apt-transport-https
          - ca-certificates
          - curl
          - zip
          - unzip
        state: present
