---
- name: fish shell PPA for Ubuntu
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  when: ansible_distribution == "Ubuntu"

- name: fish shell repo for Debian
  block:
    - name: apt source
      apt_repository:
        repo: deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_{{ansible_distribution_major_version}}/ /
        state: present
        filename: shells:fish:release:3

    - name: apt key
      apt_key:
        id: eZZ0c1k1iy5pbXClLaDKRhrWoeecrQnX
        url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_{{ansible_distribution_major_version}}/Release.key
        keyring: /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg
        state: present
  when: ansible_distribution == "Debian"
