---

- name: Nvim executeable
  stat:
    path: /usr/bin/nvim
  register: nvim_executeable

# Install nvim from AppImage.
# https://github.com/neovim/neovim/blob/master/INSTALL.md#appimage-universal-linux-package
- name: Install Neovim
  command: "{{ item }}"
  args:
    chdir: /tmp/
  with_items:
    - "curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    - "chmod u+x nvim.appimage"
    - "./nvim.appimage --appimage-extract"
    - "mv ./squashfs-root/ /opt/nvim-squashfs-root/"
    - "ln -s /opt/nvim-squashfs-root/AppRun /usr/bin/nvim"
  when: not nvim_executeable.stat.exists
